/**
 * Constantes para nombres de tablas y esquemas de la base de datos
 */

// Esquemas
export const SCHEMA_CONTABILIDADES = 'FBS_CONTABILIDADES';
export const SCHEMA_ORGANIZACIONES = 'FBS_ORGANIZACIONES';
export const SCHEMA_GENERALES = 'FBS_GENERALES';

// Tablas
export const TABLA_VISTAS = `${SCHEMA_CONTABILIDADES}.VISTAS_INDICADORES`;
export const TABLA_FORMULAS = `${SCHEMA_CONTABILIDADES}.FORMULAS`;
export const TABLA_INDICADORES = `${SCHEMA_CONTABILIDADES}.INDICADORES`;
export const TABLA_INDICADORES_CALCULADOS = `${SCHEMA_CONTABILIDADES}.INDICADORES_CALCULADOS`;
export const TABLA_CUENTACONTABLE = `${SCHEMA_CONTABILIDADES}.CUENTACONTABLE`;
export const TABLA_SALDOCONTABLE = `${SCHEMA_CONTABILIDADES}.SALDOCONTABLE`;
export const TABLA_OFICINA = `${SCHEMA_ORGANIZACIONES}.OFICINA`;
export const TABLA_DIVISION = `${SCHEMA_GENERALES}.DIVISION`;
export const TABLA_USUARIOS = `${SCHEMA_GENERALES}.USUARIOS`;

// Tablas de Notificaciones
export const TABLA_NOTIFICACIONES_CONFIG = `${SCHEMA_CONTABILIDADES}.NOTIFICACIONES_CONFIG`;
export const TABLA_CONFIGURACIONES_ENVIO = `${SCHEMA_CONTABILIDADES}.CONFIGURACIONES_ENVIO`;
export const TABLA_HISTORIAL_ENVIOS = `${SCHEMA_CONTABILIDADES}.HISTORIAL_ENVIOS`;

// Tablas de Reportes
export const TABLA_CONFIGURACIONES_REPORTES = `${SCHEMA_CONTABILIDADES}.CONFIGURACIONES_REPORTES`;